const assert = require("node:assert/strict");
const fs = require("node:fs");

const source = fs.readFileSync("server.js", "utf8");
const dashboard = fs.readFileSync("public/index.html", "utf8");
assert.match(source, /ALTER TABLE orders ADD COLUMN archive_state/);
assert.match(source, /ALTER TABLE orders ADD COLUMN archived_at/);
assert.match(source, /ALTER TABLE orders ADD COLUMN archive_reason/);
assert.match(source, /ALTER TABLE order_candidates ADD COLUMN archive_state/);
assert.match(source, /ALTER TABLE order_candidates ADD COLUMN archived_at/);
assert.match(source, /ALTER TABLE order_candidates ADD COLUMN archive_reason/);
assert.match(source, /app\.post\("\/api\/admin\/orders\/archive-open", requireAdmin/);
assert.match(source, /app\.post\("\/api\/admin\/unconfirmed-bookings\/archive-before", requireAdmin/);
assert.match(source, /ARCHIVE_OLD_UNCONFIRMED_ONLY/);
assert.match(source, /datetime\(created_at\)<datetime\(\?\)/);
assert.match(source, /Asia\/Amman/);
assert.match(source, /Only the start of the current Jordan day may be used/);
assert.match(source, /UPDATE order_candidates\s+SET archive_state='archived'/);
assert.match(source, /lifecycle_blocker='admin_archived'/);
assert.match(source, /UPDATE order_candidate_acceptances SET status='cancelled'/);
assert.match(source, /order\.candidate\.archived/);
assert.match(source, /mutation: "archive_old_unconfirmed_only"/);
assert.match(source, /financialMutation: false/);
assert.match(source, /audit\("order\.archived"/);
assert.match(source, /COALESCE\(o\.archive_state,'active'\)='active'/);
assert.match(source, /reason: "order_archived"/);
assert.match(dashboard, /value="archive-open"/);
assert.match(dashboard, /api\('\/api\/admin\/orders\/archive-open'/);
const admin = fs.readFileSync("admin.html", "utf8");
assert.match(admin, /id="unconfirmedBookingsArchiveOld"/);
assert.match(admin, /function jordanTodayStartIso\(\)/);
assert.match(admin, /api\('\/api\/admin\/unconfirmed-bookings\/archive-before'/);
assert.match(admin, /ARCHIVE_OLD_UNCONFIRMED_ONLY/);
console.log("order archive guardrails verified");
