const assert = require('assert');
const fs = require('fs');

const server = fs.readFileSync('./server.js', 'utf8');
const index = fs.readFileSync('./public/index.html', 'utf8');
const admin = fs.readFileSync('./admin.html', 'utf8');

assert.ok(server.includes('app.get("/api/admin/cards", requireAdmin'), 'admin card history API is protected');
assert.ok(server.includes('app.get("/api/admin/bulk-topup/preview", requireAdmin'), 'bulk top-up preview API is protected');
assert.ok(server.includes('app.post("/api/admin/bulk-topup/zero-balance-5", requireAdmin'), 'zero-balance five JOD bulk issue API is protected');
assert.ok(server.includes('ISSUE_ZERO_BALANCE_5_JOD_ACTIVE_GROUP_CAPTAINS'), 'zero-balance bulk issue requires explicit confirmation');
assert.ok(server.includes('wallet_cents=0'), 'zero-balance bulk issue targets exact zero balances');
assert.ok(server.includes('active=1 AND is_bot=0 AND wallet_cents=0'), 'zero-balance bulk issue excludes inactive and bot accounts');
assert.ok(server.includes('const issueKey = `ZERO5-JOD-${captain.id}`'), 'zero-balance bulk issue is idempotent per captain');
assert.ok(server.includes('app.post("/api/admin/bulk-topup/negative-one-3", requireAdmin'), 'negative-one three JOD bulk issue API is protected');
assert.ok(server.includes('ISSUE_NEGATIVE_ONE_3_JOD_ACTIVE_GROUP_CAPTAINS'), 'negative-one bulk issue requires explicit confirmation');
assert.ok(server.includes('wallet_cents=-100'), 'negative-one bulk issue targets exact negative one balances');
assert.ok(server.includes('const issueKey = `NEG3-JOD-${captain.id}`'), 'negative-one bulk issue is idempotent per captain');
assert.ok(server.includes('readOnly: true'), 'bulk top-up preview is explicitly read-only');
assert.ok(server.includes('policy: "abs_current_balance"'), 'bulk top-up preview uses absolute current balance policy');
assert.ok(server.includes('wallet_cents<>0'), 'bulk top-up preview excludes zero balances');
assert.ok(server.includes("active=1 AND account_status='active'"), 'bulk top-up preview targets active captains only');
assert.ok(server.includes('app.post("/api/admin/cards", requireAdmin'), 'admin card issuance API is protected');
assert.ok(server.includes('issue_idempotency_key'), 'card issuance persists an idempotency key');
assert.ok(server.includes('delivery_idempotency_key'), 'card delivery persists an idempotency key');
assert.ok(server.includes('cardDeliveryInFlight.has(cardId)'), 'card delivery rejects concurrent sends');
assert.ok(server.includes('renderTopupCardMedia'), 'card delivery renders an official branded image');
assert.ok(server.includes('async function resolveWhatsAppRecipientId'), 'card delivery resolves the current WhatsApp recipient id');
assert.ok(server.includes('client.getNumberId(phone)'), 'recipient resolution checks the registered WhatsApp identity');
assert.ok(server.includes('/@(c\\.us|lid)$/.test(serialized)'), 'recipient resolution accepts current LID identities');
assert.ok(server.includes('client.getContactById(`${phone}@c.us`)'), 'recipient resolution falls back to the direct WhatsApp contact');
assert.ok(server.includes('client.isRegisteredUser(phone)'), 'recipient resolution checks registered phone fallback');
assert.ok(server.includes('using text fallback'), 'operations notifications have a text fallback when media fails');
assert.ok(server.includes('const recipient = await resolveWhatsAppRecipientId(card.captain_phone);'), 'stored card delivery uses the resolved WhatsApp identity');
assert.ok(server.includes('const recipient = await resolveWhatsAppRecipientId(captain.phone);'), 'new captain card delivery uses the resolved WhatsApp identity');
assert.ok(server.includes('const recipient = await resolveWhatsAppRecipientId(phone);'), 'support top-up delivery uses the resolved WhatsApp identity');
assert.ok(server.includes('app.post("/api/admin/cards/:id/send-text", requireAdmin'), 'admin card text fallback is protected');
const walletAdjustmentBlock = server.slice(server.indexOf('async function handleAdminWalletAdjustment'), server.indexOf('app.post("/api/admin/captains/:id/wallet-adjustment"'));
assert.ok(walletAdjustmentBlock.includes('topupCardTextMessage'), 'wallet credit delivery uses the text card path');
assert.ok(walletAdjustmentBlock.includes('topup_card.sent_text_fallback'), 'wallet credit text delivery is audited safely');
assert.ok(walletAdjustmentBlock.includes('cardDeliveryInFlight.has(card.id)'), 'wallet credit delivery rejects concurrent sends');
assert.doesNotMatch(walletAdjustmentBlock, /error: String\(error\?\.message \|\| error\)/, 'wallet credit delivery does not expose raw errors');
assert.ok(server.includes('app.post("/api/admin/cards/:id/void", requireAdmin, handleVoidTopupCard)'), 'admin card cancellation is protected');
assert.ok(server.includes('if (card.sent_at) return res.status(409)'), 'recovery cancellation rejects delivered cards');
assert.ok(server.includes("WHERE id=? AND status='issued' AND sent_at IS NULL"), 'recovery cancellation mutates only unsent issued cards');
assert.ok(server.includes('function topupCardTextMessage'), 'card text fallback has a dedicated formatter');
assert.ok(server.includes('topup_card.sent_text_fallback'), 'text fallback delivery is audited without exposing the code');
assert.ok(server.includes('res.json({ success: true, status: "sent", deliveryMode });'), 'delivery response does not expose the card code');
const deliveryBlock = server.slice(server.indexOf('function topupCardTextMessage'), server.indexOf('app.post("/api/redeem"'));
assert.ok(deliveryBlock.indexOf('if (!sent) return res.status(504)') < deliveryBlock.indexOf('UPDATE topup_cards SET sent_at=?'), 'sent_at is updated only after WhatsApp confirms delivery');
assert.doesNotMatch(deliveryBlock, /@c\.us/, 'stored card delivery must not force a legacy c.us recipient id');
assert.doesNotMatch(deliveryBlock, /console\.(?:log|error)[^\n]*code/, 'card code must not be written to console logs');
assert.doesNotMatch(deliveryBlock, /audit\([^\n]*\bcode\b/, 'card code must not be written to audit logs');
assert.ok(server.includes('const appUrl = captainAppUrl(captainInviteBaseUrl(req))'), 'card message contains the official operations gateway');
assert.ok(server.includes('app.post("/api/captain/redeem-card", requireCaptain'), 'captain session redemption API exists');
assert.ok(server.includes('source: "captain_portal"'), 'portal redemption is audited');
assert.ok(server.includes('if (!cardEncryptionKey) return res.status(503)'), 'card issuance requires encryption');
assert.ok(server.includes('app.post("/api/redeem"'), 'captain redemption endpoint remains available');
assert.ok(index.includes('id="generate-card"'), 'owner card issuance control exists');
assert.ok(index.includes('crypto.randomUUID()'), 'owner UI creates request idempotency keys');
assert.ok(index.includes('/api/admin/cards?limit=12'), 'owner UI reads recent card history');
assert.ok(index.includes('id="topup-history-refresh"'), 'owner UI provides history refresh');
assert.ok(server.includes('cards_issued_cents'), 'admin users API includes issued card totals');
assert.ok(server.includes('cards_sent_cents'), 'admin users API includes sent card totals');
assert.ok(server.includes('cards_redeemed_cents'), 'admin users API includes redeemed card totals');
assert.ok(server.includes('cards_pending_cents'), 'admin users API includes pending card totals');
assert.ok(admin.includes('البطاقات المصدرة'), 'admin users table shows issued card totals');
assert.ok(admin.includes('البطاقات المرسلة'), 'admin users table shows sent card totals');
assert.ok(admin.includes('البطاقات المستردة'), 'admin users table shows redeemed card totals');
assert.ok(admin.includes('بطاقات معلّقة'), 'admin users table shows pending card totals');
assert.ok(admin.includes('إرسال WhatsApp'), 'admin users table includes WhatsApp action');
assert.ok(index.includes('data-card-history-send'), 'owner UI provides controlled resend action');
assert.ok(index.includes("'/api/admin/cards/'+encodeURIComponent(cardId)+'/send-text'"), 'owner UI uses the reliable text resend endpoint');
assert.ok(index.includes('https://whatsapserver-2.onrender.com/join.html'), 'owner invite points to the official operations gateway');
assert.ok(fs.readFileSync('./public/captain.html', 'utf8').includes('id="topup-redeem-form"'), 'captain app has a redemption form');
assert.ok(fs.readFileSync('./public/captain.html', 'utf8').includes('/api/captain/redeem-card'), 'captain app submits redemption to the session API');
assert.ok(fs.readFileSync('./public/captain.html', 'utf8').includes('renderTopupCards'), 'captain app renders card notifications');
console.log('top-up API guardrails verified');
