const assert = require("assert/strict");
const fs = require("fs");
const path = require("path");

const server = fs.readFileSync(path.join(__dirname, "server.js"), "utf8");
assert.match(server, /CREATE TABLE IF NOT EXISTS order_candidates/);
assert.match(server, /function createOrderCandidate\(/);
assert.match(server, /findOrderByQuotedMessage\(groupId, quoted\)/);
assert.match(server, /status='pending',pending_captain_user_id/);
assert.match(server, /function settlePendingOrder\(candidateId, expectedMessageId, confirmerPhone\)/);
assert.match(server, /INSERT INTO orders\(order_no,source_message_id/);
assert.match(server, /status IN \('accepted','completed'\)/);
assert.match(server, /app\.get\("\/api\/admin\/orders", requireAdmin/);
assert.match(server, /const pendingConfirmation = 0/);
assert.match(server, /void sendFinalBookingConfirmation\(target\.from, \{ orderNo: result\.order\?\.order_no/);
assert.match(server, /function finalBookingConfirmationText\(\{ orderNo, executorName, consumerName, priceCents \}\)/);
assert.match(server, /\.slice\(0, 40\)/);
assert.doesNotMatch(server, /sendGroupBrandedMessage\(groupId, "تم تسجيل الطلب"/);
assert.doesNotMatch(server, /sendGroupBrandedMessage\(groupId, "بانتظار اعتماد كابتن تنزيل الطلب"/);
assert.doesNotMatch(server, /client\.sendMessage\(target\.from, `تم تثبيت الطلب:/);
assert.match(server, /const candidate = quoted/);
assert.match(server, /findLatestStandaloneAcceptanceCandidate\(groupId\)/);
assert.match(server, /const botCompanyApproval = isBotPhone\(approverPhone\) && BOT_FINANCIAL_MODE === "company"/);
assert.match(server, /const approver = botCompanyApproval \? companyUser\(\) : findActiveRegisteredUser\(approverPhone\)/);
assert.match(server, /phoneWithCountry\(producer\.phone\) !== phoneWithCountry\(approverPhone\)/);
assert.match(server, /confirmingCaptainFeeCents/);
console.log("hidden candidate confirmation guardrails verified");
