const assert = require('node:assert/strict');
const fs = require('node:fs');
const server = fs.readFileSync('server.js', 'utf8');

assert.match(server, /function acceptanceBalanceGuard\(candidate, captain\)/);
assert.match(server, /state: "insufficient_balance"/);
assert.match(server, /balanceCents < requiredCents/);
assert.match(server, /acceptanceBalanceGuard\(candidate, captain\)/);
assert.match(server, /if \(acceptanceResult\.state === "insufficient_balance"\)/);
assert.match(server, /acceptanceMode,/);
const rejectionStart = server.indexOf('if (acceptanceResult.state === "insufficient_balance")');
const rejectionEnd = server.indexOf('if (["captain_ineligible"', rejectionStart);
assert.match(server.slice(rejectionStart, rejectionEnd), /deleteWhatsAppMessageForEveryone\(messageId, \{/);
assert.match(server.slice(rejectionStart, rejectionEnd), /message: msg/);
assert.doesNotMatch(server.slice(rejectionStart, rejectionEnd), /reactToCaptainAcceptance\(msg, messageId, "❌"\)/);
assert.match(server, /order\.acceptance_rejected_insufficient_balance/);
assert.match(server, /messageDeletionRequested/);
assert.match(server, /\[WhatsApp\]\[MessageDelete\] start/);
assert.match(server, /\[WhatsApp\]\[MessageDelete\] \$\{outcome\}/);
assert.match(server, /reason: "insufficient_balance_acceptance"/);
const deleteGuardBlock = server.slice(rejectionStart, rejectionEnd);
assert.doesNotMatch(deleteGuardBlock, /if \(typeof msg\?\.delete === "function"\)/, 'deletion must not be skipped when the message object lacks delete()');
assert.match(deleteGuardBlock, /try \{\s*deletionResult = await deleteWhatsAppMessageForEveryone\(messageId, \{/s);
assert.match(server, /whatsapp\.message_deletion/);
assert.match(server, /function messageIdCandidates\(message\)/);
assert.match(server, /for \(const messageId of messageIds\) recentWhatsAppMessages\.set\(messageId/);
assert.match(server, /messageIdCandidates: messageIdCandidates\(msg\)/);
assert.match(server, /const requestedMessageIds = \[\.\.\.new Set\(/);
assert.match(server, /requestedMessageIds\.flatMap\(\(value\) => messageIdLookupVariants\(value\)\)/);
assert.match(server, /const lookupIds = \[\.\.\.new Set\(/);
assert.match(server, /collections\.Msg\.getMessagesById\(ids\)/);
assert.match(server, /originalMessage\.delete\(true\)/);
assert.match(server, /method: "message\.delete"/);
assert.match(server, /async function verifyWhatsAppMessageDeletion\(message, messageId/);
assert.match(server, /const verification = await verifyWhatsAppMessageDeletion\(originalMessage, messageId\)/);
assert.match(server, /const deleteAcknowledged = verification\.verified/);
assert.match(server, /deleteReturn=\$\{deletedFromSearch !== false\} verification=\$\{verification\.reason\}/);
assert.match(server, /reason: "message_still_present"/);
assert.match(server, /reason: "revoked_after_reload"/);
assert.match(server, /const directDeleteDelays = \[0, 400, 1000\]/);
assert.match(server, /attempt=\$\{attempt \+ 1\}\/\$\{directDeleteDelays\.length\}/);
assert.match(server, /const recentWhatsAppMessages = new Map\(\)/);
assert.match(server, /cacheIncomingWhatsAppMessage\(msg\)/);
assert.match(server, /const originalMessage = context\.message \|\| getCachedIncomingWhatsAppMessage\(messageId\)/);
assert.match(server, /typeof msg\?\.getContact !== "function"/);
assert.match(server, /originalMessage\.getChat\(\)/);
assert.doesNotMatch(server, /chat\.fetchMessages\(\{ limit: 50 \}\)/);
assert.match(server, /chat_history_lookup/);
assert.match(server, /chat\.fetchMessages\.message\.delete/);
assert.match(server, /chat\.fetchMessages\(\{ limit: 100 \}\)/);
assert.match(server, /chat_history_unique_text_fallback/);
assert.match(server, /chat_history_text_ambiguous/);
assert.match(server, /client\.searchMessages\("تم", \{ page: 0, limit: 100, chatId: deletionContext\.groupId \}\)/);
assert.match(server, /search_unique_acceptance_fallback/);
assert.match(server, /searchMessages\.message\.delete/);
assert.match(server, /search_acceptance_fallback_\$\{searchCandidates\.length > 1 \? "ambiguous" : "not_found"\}/);
const registerStart = server.indexOf('function registerAcceptance');
const guardIndex = server.indexOf('acceptanceBalanceGuard(candidate, captain)', registerStart);
const insertIndex = server.indexOf('INSERT INTO order_candidate_acceptances', registerStart);
assert.ok(registerStart >= 0 && guardIndex >= 0 && insertIndex > guardIndex, 'balance guard runs before acceptance insert');
const recoveryStart = server.indexOf('if (unquotedResult?.state === "insufficient_balance")');
const recoveryEnd = server.indexOf('if (!unquotedResult ||', recoveryStart);
assert.ok(recoveryStart >= 0 && recoveryEnd > recoveryStart, 'unquoted recovery balance rejection must exist');
assert.match(server.slice(recoveryStart, recoveryEnd), /deleteWhatsAppMessageForEveryone\(rowMessageId, \{/);
assert.match(server.slice(recoveryStart, recoveryEnd), /message: acceptance/);
assert.match(server.slice(recoveryStart, recoveryEnd), /acceptanceMode: "unquoted"/);
console.log('insufficient balance blocks and revokes captain acceptance');
