const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('server.js', 'utf8');
assert.match(source, /async function fetchInternalReactionRows\(messageId\)/);
assert.match(source, /WAWebCollections/);
assert.match(source, /collections\.Reactions\.find\(candidateId\)/);
assert.match(source, /const fullId = String\(targetId \|\| ""\)/);
assert.match(source, /const rawId = parts\.slice\(2\)\.join\("_"\)/);
assert.match(source, /const coreId = parts\[2\] \|\| ""/);
assert.match(source, /const participantId = parts\[parts\.length - 1\] \|\| ""/);
assert.match(source, /const messageIds = \[\.\.\.new Set\(\[fullId, rawId, coreId, participantId\]/);
assert.match(source, /function messageIdLookupVariants\(value\)/);
assert.match(source, /async function getWhatsAppMessageByIdVariants\(value, timeoutMs = 6000\)/);
assert.match(source, /getWhatsAppMessageByIdVariants\(messageId, 5000\)/);
assert.match(source, /reaction\.emoji \|\| reaction\?\._data\?\.emoji/);
assert.match(source, /if \(Array\.isArray\(value\)\) return value/);
assert.match(source, /if \(Array\.isArray\(value\.models\)\) return value\.models/);
assert.match(source, /collections\.Msg\?\.getMessagesById/);
assert.match(source, /const internalReactions =/);
assert.match(source, /internalReactions\.length && !archivedHasSenders/);
const reconcileStart = source.indexOf('async function reconcileStoredThumbReaction(');
const reconcileEnd = source.indexOf('function parseCookies(', reconcileStart);
assert.ok(reconcileStart >= 0 && reconcileEnd > reconcileStart, 'reconcile function must be present');
const reconcileSource = source.slice(reconcileStart, reconcileEnd);
assert.match(reconcileSource, /let reactions = await withTimeout\(target\.getReactions\(\), 12000, \[\]\);/);
assert.match(reconcileSource, /const internalReactions = await fetchInternalReactionRows\(messageId\)/);
assert.match(reconcileSource, /reactions = internalReactions/);
console.log('internal reaction rows guard: ok');
