const assert = require("assert");
const fs = require("fs");

const source = fs.readFileSync("./server.js", "utf8");
const handlerStart = source.indexOf("async function handleIncomingMessage(msg, { allowSelf = false } = {})");
const handlerEnd = source.indexOf("function reactionId(", handlerStart);
assert(handlerStart >= 0 && handlerEnd > handlerStart, "معالج رسائل القروب موجود");
const handler = source.slice(handlerStart, handlerEnd);
const logPosition = handler.indexOf("INSERT OR IGNORE INTO messages");
const botFilterPosition = handler.indexOf("if (botGenerated && !parseOrder(body).isOrder) return;");
assert(logPosition >= 0, "رسائل القروب تُحفظ في جدول messages");
assert(botFilterPosition >= 0 && botFilterPosition < logPosition, "رسائل البوت العادية تُستبعد قبل الحفظ");
assert(handler.includes("if (!insertedMessage.changes && !captainAcceptance) return;"), "الرسائل المكررة العادية لا تعاد معالجتها تشغيليًا");
assert(handler.includes("acceptance_message_replayed_after_duplicate_guard"), "رسائل تم المكررة يمكن إعادة ربطها بالقبول");
assert(source.includes('app.get("/api/admin/group-messages", requireAdmin'), "واجهة قراءة السجل محمية إداريًا");
const sendFinalizer = source.slice(source.indexOf("function finalizeAdminSentMessage"), source.indexOf("function currentCaptainSubscriptionPeriod"));
const sendRoute = source.slice(source.indexOf('app.post("/api/admin/send"'), source.indexOf("function reconcileConfiguredGroupFromEnvironment"));
assert(sendFinalizer.includes('isConfiguredGroup(chatId) && messageId'), "لا يُنشأ مرشح إداري دون معرّف WhatsApp حقيقي");
assert(sendRoute.includes("completeAdminSend"), "مسار الإرسال يستخدم إنهاء الرسالة الموحد");
assert(source.includes("observeAdminSentMessage(msg)"), "حدث message_create يمكنه تأكيد الإرسال المتأخر");
assert(!sendRoute.includes("admin-send-${Date.now()}"), "لا تُستخدم معرّفات مؤقتة تفصل المرشح عن رسالة WhatsApp");
console.log("group message logging guardrails verified");
