const assert = require("assert/strict");
const fs = require("fs");
const server = fs.readFileSync("server.js", "utf8");
const admin = fs.readFileSync("admin.html", "utf8");
const staff = fs.readFileSync("public/staff.html", "utf8");
const captain = fs.readFileSync("public/captain.html", "utf8");
assert.match(server, /posted_share_cents/);
assert.match(server, /executed_debit_cents/);
assert.match(server, /postedShare: money/);
assert.match(server, /executedDebit: money/);
assert.match(server, /settlement_state='settled'/);
assert.match(server, /LEFT JOIN order_settlements s ON s.order_id=o.id/);
assert.ok(server.includes('app.get("/api/admin/wallets"'));
assert.ok(server.includes('app.get("/api/staff/wallets"'));
assert.match(admin, /openCaptainProfile/);
assert.match(admin, /captainSearch/);
assert.match(admin, /renderCaptains/);
assert.match(admin, /خصم التنفيذ/);
assert.match(staff, /executorDebit/);
assert.match(staff, /companyShare/);
assert.match(captain, /posted-share/);
assert.match(captain, /executedDebit/);
console.log("settlement visibility guardrails verified");
