const assert = require('assert');
const fs = require('fs');

const server = fs.readFileSync('./server.js', 'utf8');
const index = fs.readFileSync('./public/index.html', 'utf8');

assert(server.includes('async function sendCompanyOperationsCard'), 'company card sender exists');
assert(server.includes('renderOperationsMessageMedia(title, lines)'), 'individual company replies render branded media');
assert(server.includes('async function sendBotText(to, text)'), 'text API is preserved as a compatibility wrapper');
assert(server.includes('return sendCompanyOperationsCard(to, "رسالة رسمية من شركة الجراح", lines)'), 'ordinary company messages use the official card');
assert(server.includes('sendCaptainOperationsCard(`${phoneWithCountry(invite.phone)}@c.us`, "تم اعتماد تسجيل الكابتن"'), 'captain approval is sent as a branded card');
assert(server.includes('app.post("/api/admin/captains/resend-access-card", requireAdmin'), 'admin can safely resend the official captain access card');
assert(server.includes('message?.fromMe && !message?.hasMedia'), 'cleanup targets only a previous outgoing plain-text reply');
assert(server.includes('previous.delete(true)'), 'previous plain reply may be deleted for everyone when WhatsApp permits it');
assert(server.includes('CREATE TABLE IF NOT EXISTS notifications'), 'notification delivery state is persisted');
assert(server.includes('async function notifyOperations'), 'owner and captain notification service exists');
assert(server.includes('app.get("/api/admin/notifications", requireAdmin'), 'owner can read notification history');
assert(server.includes('system.settings.updated'), 'system settings changes notify the owner');
assert(server.includes('topup_card.redeemed'), 'wallet redemption notifies captain and owner');
assert(server.includes('group.configured'), 'group configuration notifies the owner');
assert(server.includes('captains.group_membership.bulk_sync'), 'captain synchronization notifies the owner');
assert(server.includes('whatsapp.reconnect.requested'), 'reconnect requests notify the owner');
assert(server.includes('captain.activated'), 'captain status changes notify captain and owner');
assert(server.includes('operations card not sent because branded media failed'), 'plain-text fallback is disabled for individual company messages');
assert(server.includes('group operations card not sent because branded media failed'), 'plain-text fallback is disabled for group messages');
assert(server.includes('const media = await renderTopupCardMedia({ cardId: card.lastInsertRowid'), 'top-up request fulfillment renders a card image');
assert(server.includes('client.sendMessage(`${phone}@c.us`, media, { caption })'), 'top-up request sends the generated card in the same action');
assert(index.includes('.hero-card{padding:17px 20px'), 'owner request console is compact');
assert(index.includes('id="topup-requests-open"'), 'top-up requests remain accessible from the compact console');
assert(index.includes('data-topup-fulfill'), 'top-up approval remains a single fulfill-and-send action');
assert(index.includes('data-captain-access-card'), 'captain rows include an official access-card resend action');
assert(index.includes("sessionStorage.getItem(onceKey)"), 'URL-triggered resend is guarded against duplicate execution in the same browser session');
assert(index.includes('id="ops-register-members"'), 'owner can register current group members from the WhatsApp drawer');
assert(index.includes("/api/admin/group/register-members"), 'group registration action sends official access cards');
assert(index.includes("params.get('registerGroupMembers')==='1'"), 'group registration can be launched once from the authenticated owner page');
assert(index.includes("/api/admin/group/send-guide-videos"), 'guide videos can be sent to the configured group');
assert(server.includes('app.post("/api/admin/group/send-guide-videos", requireAdmin'), 'guide video group API is admin protected');
assert(server.includes('app.get("/api/admin/group/diagnostic", requireAdmin'), 'group diagnostic API is admin protected');
assert(server.includes('client.getInviteInfo(inviteCode)'), 'group relink verifies the invite before accepting it');
assert(server.includes('membersLoaded: groupChat.participants.length'), 'group relink reports loaded member count');
assert(server.includes('function resolveGroupChat(groupId, inviteCode = "")'), 'group registration retries group hydration');
assert(server.includes('async function readGroupSnapshot(groupId)'), 'group membership can be read from the WhatsApp page model');
assert(server.includes('queryAndUpdateGroupMetadataById({ id: requestedId })'), 'group snapshot refreshes WhatsApp group metadata');
assert(server.includes('async function mediaFromRemoteVideoUrl(url, index = 0)'), 'guide videos download through a bounded temporary file');
assert(server.includes('MessageMedia.fromFilePath(temporaryPath)'), 'guide videos are converted from the downloaded local file');
assert(server.includes('app.get("/api/admin/diagnostics/last-guide-video-send", requireAdmin'), 'guide video send telemetry is admin protected');
assert(server.includes('waitUntilMsgSent: true'), 'guide video delivery waits for WhatsApp send confirmation');
assert(server.includes('errors.push({ index, error:'), 'guide video failures expose a bounded diagnostic reason');
assert(server.includes('client.sendMessage(groupId, media'), 'guide videos send through the stable WhatsApp client API');
assert(server.includes('async function sendGroupMemberInvitesInBackground'), 'group member invitations have a separate safe background flow');
assert(server.includes('app.get("/api/admin/group/send-member-invites", requireAdmin'), 'member invite delivery is admin protected');
assert(server.includes('group.member.invite'), 'member invite delivery is persisted as a notification event');
assert(server.includes('هذا ليس تسجيل كابتن جديدًا'), 'member invite card explains captain login instead of new registration');
assert(server.includes('groupInviteInFlight'), 'member invite delivery is protected from duplicate execution');
assert(server.includes('sharp.concurrency(1)'), 'card rendering limits native image concurrency');
assert(server.includes('const inviteCardMedia = await withTimeout(renderOperationsMessageMedia(title, lines)'), 'invite cards reuse one rendered media asset per batch');
assert(server.includes('app.get("/api/admin/group/use-original", requireAdmin'), 'original WhatsApp group can be reactivated safely');
assert(server.includes('const groupId = "120363426604560611@g.us"'), 'original active group id is explicit');
assert(server.includes('UPDATE groups_config SET active=0,updated_at=? WHERE group_id<>?'), 'new or historical groups are deactivated without deletion');
assert(server.includes('newGroupUnused: true'), 'relink response confirms the new group is unused');
assert(server.includes('app.get("/api/admin/group/delete-unapproved", requireAdmin'), 'unapproved group deletion is admin protected');
assert(server.includes('const newGroupId = "120363413760988742@g.us"'), 'deletion target is the known new group only');
assert(server.includes('if (groupId === originalGroupId || groupId === getSetting("group_id", null))'), 'active original group is protected from deletion');
assert(server.includes('originalGroupUntouched: true'), 'deletion response confirms original group remains untouched');
assert(server.includes("role='producer',is_bot=1,active=1"), 'the bot owner phone is normalized as the company producer');
assert(server.includes('captain_pin_hash=NULL,captain_pin_ciphertext=NULL'), 'the bot owner cannot retain captain login credentials');
assert(server.includes('app.get("/api/admin/captains", requireAdmin, (req, res) => {\n  normalizeBotIdentity();'), 'captain list normalizes the owner before returning data');
assert(server.includes('الخطوة 2: اختر «دخول الكابتن»'), 'captain card explains the exact login choice');
console.log('official company card and compact top-up flow guardrails verified');
