const assert = require("assert/strict");
const fs = require("fs");
const path = require("path");
const server = fs.readFileSync(path.join(__dirname, "server.js"), "utf8");
assert.match(server, /const removedThumb = reactionValue === ""/);
assert.match(server, /order_candidates WHERE group_id=\? AND status='pending'/);
assert.match(server, /status='cancelled',pending_captain_user_id=NULL/);
assert.match(server, /status IN \('accepted','completed'\) AND accepted_message_id=\?/);
assert.match(server, /cancelOrderForReactionRemoval\(order\.id, messageId, approverPhone\)/);
assert.match(server, /status='cancelled',settlement_state='reversed'/);
assert.match(server, /UPDATE order_settlements SET status='reversed'/);
assert.match(server, /reversal_company/);
assert.match(server, /reversal_producer/);
assert.match(server, /reversal_captain_fee/);
assert.match(server, /sendFinalBookingCard\(target\.from, result\.producer\?\.name, result\.captain\?\.name, result\.order\?\.price_cents\)/);
assert.doesNotMatch(server, /client\.sendMessage\(target\.from, `تم تثبيت الطلب:/);
assert.doesNotMatch(server, /client\.sendMessage\(target\.from, `تم إلغاء الطلب:/);
console.log("candidate cancellation and final-card reversal guardrails verified");
