const assert = require('node:assert/strict');
const fs = require('node:fs');
const server = fs.readFileSync('server.js', 'utf8');
const start = server.indexOf('app.post("/api/admin/captains/reset-pin-selective"');
const end = server.indexOf('app.post("/api/admin/group/reset-active-captain-pins"');
assert.ok(start >= 0 && end > start, 'selective owner route must exist before legacy route');
const route = server.slice(start, end);
assert.match(route, /requireAdmin/);
assert.match(server, /const SELECTIVE_CAPTAIN_PIN_CONFIRMATION = "RESET_ALL_CAPTAIN_PINS_SELECTIVE_TO_00000"/);
assert.match(route, /expectedTotalCaptainAccounts/);
assert.match(route, /COALESCE\(account_status,''\)<>'merged'/);
assert.match(route, /bcrypt\.compareSync\("00000"/);
assert.match(route, /bcrypt\.hashSync\("00000", 10\)/);
assert.match(server, /const SELECTIVE_CAPTAIN_PIN_EVENT = "captain\.pin_reset\.selective"/);
assert.match(route, /CAPTAIN-PIN-00000-/);
assert.match(route, /notifications/);
assert.match(server, /async function sendCaptainPinNoticeAtMostOnce/);
assert.match(route, /sendCaptainPinNoticeAtMostOnce/);
assert.match(route, /groupMessageSent: 0/);
assert.match(route, /financialMutation: false/);
assert.doesNotMatch(route, /groupId/);
assert.doesNotMatch(route, /chat\.sendMessage/);
assert.doesNotMatch(route, /sendMessage\(/);
assert.match(server, /stored\.role !== \"captain\"/);
assert.match(server, /stored\.account_status \|\| \"\"/);
assert.doesNotMatch(route, /wallet_cents|wallet_ledger|order_settlements|settle/i);
assert.doesNotMatch(route, /console\.(?:log|error)[^\n]*00000/);
assert.doesNotMatch(route, /eval\s*\(|new\s+Function\s*\(/);
console.log('selective captain PIN reset route guard verified');
