const assert = require("node:assert/strict");
const fs = require("node:fs");

const server = fs.readFileSync("./server.js", "utf8");
const admin = fs.readFileSync("./admin.html", "utf8");

assert.match(server, /const CAPTAIN_LOW_BALANCE_WARNING_CENTS = Number\(process\.env\.CAPTAIN_LOW_BALANCE_WARNING_CENTS \|\| 100\)/);
assert.match(server, /async function notifyCaptainLowBalance\(/);
assert.match(server, /event='captain\.wallet\.low_balance'/);
assert.match(server, /async function enforceCaptainWalletThresholds\(/);
assert.match(server, /async function enforceCaptainWalletThresholdsForAll\(/);
assert.match(server, /app\.post\("\/api\/admin\/captains\/enforce-wallet-policy", requireAdmin/);
assert.match(server, /REMOVE_NEGATIVE_CAPTAINS_NOW/);
assert.match(server, /captainWalletPolicySweepInFlight/);
assert.match(admin, /enforceNegativeWalletPolicy/);
assert.match(admin, /REMOVE_NEGATIVE_CAPTAINS_NOW/);
assert.match(admin, /دون تغيير الرصيد/);
assert.match(server, /CAPTAIN_BALANCE_POLICY_INTERVAL_MS/);
assert.match(server, /async function suspendMemberForDebt\(/);
assert.match(server, /async function readGroupRemovalContext\(/);
assert.match(server, /Number\(balanceCents\) >= 0/);
assert.match(server, /isConfiguredGroup\(officialGroupId\)/);
assert.match(server, /client\.getChats\(\)/);
assert.match(server, /readGroupSnapshot\(officialGroupId\)/);
assert.match(server, /snapshotParticipants/);
assert.match(server, /typeof chat\.removeParticipants !== "function"/);
assert.match(server, /const runSweepWhenReady = \(\) =>/);
assert.match(server, /if \(!client \|\| !isReady\) return false/);
assert.match(server, /ready-triggered sweep/);
assert.match(server, /function scheduleOfficialGroupWalletSweep/);
assert.match(server, /scheduleOfficialGroupWalletSweep\("message"\)/);
assert.match(server, /account_status='suspended'/);
assert.match(server, /getNumberId\(normalized\)/);
assert.match(server, /removeParticipants\(\[\.\.\.targetIds\]\)/);
assert.match(server, /getContactLidAndPhone\(lidIds\)/);
assert.match(server, /findPersistedWhatsappPhone\(entry\.id\)/);
assert.match(server, /if \(!targetIds\.size\) try/);
assert.match(server, /account_status IN \('active','suspended'\)/);
assert.match(server, /negativeOnly: true/);
assert.match(server, /wallet_policy_last_run/);
assert.match(server, /negativeWalletCount/);
assert.match(server, /failureStatuses/);
assert.match(server, /firstFailure/);
assert.match(server, /app\.get\("\/api\/admin\/captains\/enforce-wallet-policy\/:runKey"/);
assert.match(server, /member\.suspended_for_negative_balance/);
assert.match(server, /orderSettlementDebtPolicy: "negative balances allowed; 15% debit remains applied"/);
assert.match(server, /skipped_negative_balance/);
assert.match(server, /sendWhatsAppAtMostOnce\(recipient, message/);

const threshold = 100;
const classify = (balanceCents) => balanceCents < 0 ? "remove_and_due_message" : balanceCents < threshold ? "warning" : "normal";
assert.equal(classify(-1), "remove_and_due_message");
assert.equal(classify(0), "warning");
assert.equal(classify(99), "warning");
assert.equal(classify(100), "normal");

console.log("wallet threshold warning, negative-balance removal, official-group guard, and idempotent send guard verified");
