const assert = require("assert");
const fs = require("fs");

const source = fs.readFileSync("./server.js", "utf8");
assert(source.includes("async function registerGroupMembersAsCaptains"), "تسجيل أعضاء القروب موجود");
assert(source.includes("chat.participants"), "يقرأ أعضاء القروب الحاليين");
assert(source.includes("async function resolveGroupParticipantPhone"), "يحل معرف LID إلى رقم الهاتف الحقيقي");
assert(source.includes("resolveWhatsappUserPhone(contact"), "يستخدم محول هوية واتساب الموثوق");
assert(source.includes("function activateHumanCaptainAccount"), "يوحد تسجيل وتفعيل حساب الكابتن");
assert(source.includes("role='captain',active=1,is_bot=0,account_status='active'"), "يحوّل المستخدم البشري المؤهل إلى كابتن نشط");
assert(source.includes("isProtectedOwnerIdentity"), "يستثني حساب المالك والنظام من التحويل");
assert(source.includes('app.post("/api/admin/group/register-members", requireAdmin'), "مسار التسجيل محمي إداريًا");
assert(source.includes('app.post("/api/admin/captains/normalize-all", requireAdmin'), "يوجد مسار محمي لتثبيت جميع الحسابات الحالية");
assert(source.includes('CAPTAIN_NORMALIZATION_VERSION = "all-group-members-captains-v1"'), "التطبيع التلقائي إصدار واحد ولا يتكرر بعد النجاح");
assert(source.includes("sendLinks: false, reactivate: true"), "التطبيع الشامل صامت ويعيد تفعيل الحسابات الحالية");
assert(source.includes("function reconcileCaptainLinksWithoutSettlement"), "يربط الطلبات القديمة بالحسابات بعد تثبيتها");
assert(source.includes("financialSettlementsApplied: 0"), "لا ينفذ تسويات مالية أثناء إصلاح الهوية");
assert(source.includes("activeRegistered: activeCaptains"), "يعرض عدد الكباتن النشطين للتحقق المباشر");
assert(source.includes("nonCaptainHumanAccounts: nonCaptainHumans"), "يعرض أي حساب بشري خارج دور الكابتن");
assert(source.includes("acceptedUnlinked: Number(orderLinkStats.accepted_unlinked || 0)"), "يفصل الطلبات المقبولة غير المرتبطة عن الطلبات المفتوحة الطبيعية");
assert(!source.includes("pre-captain-normalization-"), "لا ينشئ التطبيع نسخًا احتياطية إضافية");
assert(!source.includes("skipped_existing_role"), "لا يرفض المستخدم القديم بسبب مسماه السابق");
console.log("group member registration guardrails verified");
