const assert = require("assert/strict");
const fs = require("fs");
const path = require("path");

const server = fs.readFileSync(path.join(__dirname, "server.js"), "utf8");
const confirmationStart = server.indexOf("function finalBookingConfirmationText(");
const confirmationEnd = server.indexOf("function finalBookingCancellationText", confirmationStart);
const confirmationBody = server.slice(confirmationStart, confirmationEnd);
assert.match(server, /CREATE TABLE IF NOT EXISTS order_candidates/);
assert.match(server, /function createOrderCandidate\(/);
assert.match(server, /startsWithPriceKeyword = \/\^السعر/);
assert.match(server, /function isCaptainAcceptance\(text\)/);
assert.match(server, /const cancellationReaction = reactionValue === "❌"/);
assert.match(server, /function cancelPendingOrderForProducerReaction\(/);
assert.match(server, /findOrderByQuotedMessage\(groupId, quoted\)/);
assert.match(server, /status='pending',pending_captain_user_id/);
assert.match(server, /function settlePendingOrder\(candidateId, expectedMessageId, confirmerPhone, \{ adminApproval = false \} = \{\}\)/);
assert.match(server, /INSERT INTO orders\(order_no,source_message_id/);
assert.match(server, /status IN \('accepted','completed'\)/);
assert.match(server, /app\.get\("\/api\/admin\/orders", requireAdmin/);
assert.match(server, /const pendingConfirmation = 0/);
assert.match(server, /void sendFinalBookingConfirmation\(target\.from, \{ orderNo: result\.order\?\.order_no/);
assert.match(server, /function finalBookingConfirmationText\(\{ orderNo, executorName, downloaderName, consumerName, priceCents \}\)/);
assert.match(confirmationBody, /return `✅ تم تثبيت الطلب #\$\{String\(orderNo \|\| "غير محدد"\)\}`;/);
assert.doesNotMatch(confirmationBody, /شامل العمولة|الكابتن المنفذ:|مقبول ومعتمد|صاحب الطلب:/);
assert.match(server, /function finalBookingConfirmationOrderNo\(body\)/);
assert.match(server, /const shortMatch = text\.match\(\/\^✅ تم تثبيت الطلب\\s\*#\(\\d\+\)\$\//);
assert.match(server, /function finalBookingCancellationText\(\)/);
assert.match(server, /❌ تم رفض أو إلغاء الطلب/);
assert.doesNotMatch(server, /sendGroupBrandedMessage\(groupId, "تم تسجيل الطلب"/);
assert.doesNotMatch(server, /sendGroupBrandedMessage\(groupId, "بانتظار اعتماد كابتن تنزيل الطلب"/);
assert.doesNotMatch(server, /client\.sendMessage\(target\.from, `تم تثبيت الطلب:/);
assert.match(server, /typeof raw === "string" \? raw : ""/);
assert.match(server, /let candidate = quoted/);
assert.match(server, /findUnquotedAcceptanceCandidate\(groupId, senderPhone/);
assert.doesNotMatch(server, /findLatestStandaloneAcceptanceCandidate\(groupId\)/, "لا يربط تم غير المقتبس بآخر طلب بشكل تخميني");
assert.match(server, /const acceptanceCaptain = pending\.captain_user_id/);
assert.match(server, /const settlementConfirmerPhone = phoneWithCountry\(acceptanceCaptain\.phone\)/);
assert.match(server, /const result = settlePendingOrder\(pending\.candidate_id, pending\.acceptance_message_id, settlementConfirmerPhone\)/);
assert.doesNotMatch(server, /const producerApproved =/);
assert.match(server, /reactionIsByCurrentAccount/);
assert.match(server, /reaction sender mapped to connected bot from self-reaction evidence/);
assert.match(server, /function reactionSenderValues\(reaction\)/);
assert.match(server, /isConnectedBotReactionIdentity/);
assert.match(server, /reaction sender resolved from LID mapping/);
assert.match(server, /reaction_approver_identity_unresolved/);
assert.match(server, /hasReactionByMe: storedReaction\?\.hasReactionByMe === true/);
assert.match(server, /if \(reactionValue === "👍" \|\| reactionValue === "❌"\)/);
assert.doesNotMatch(server, /hasVisibleThumbReaction\(messageId\)\)[\s\S]{0,180}hasReactionByMe: true/);
assert.match(server, /if \(!senders\.length\)/);
assert.match(server, /if \(await hasVisibleThumbReaction\(messageId\)\)/);
assert.doesNotMatch(server, /if \(!target \|\| !target\.hasReaction \|\| typeof target\.getReactions !== "function"\) return;/);
assert.match(server, /async function recoverPendingAcceptanceMessages\(groupId\)/);
assert.match(server, /async function recoverHistoricalOrderCandidates\(groupId\)/);
assert.match(server, /whatsappHistoricalCandidateRecoveryAttempted/);
assert.match(server, /WHATSAPP_HISTORICAL_CANDIDATE_RECOVERY_INTERVAL_MS/);
assert.match(server, /Date\.now\(\) - whatsappHistoricalCandidateRecoveryAt < WHATSAPP_HISTORICAL_CANDIDATE_RECOVERY_INTERVAL_MS/);
assert.match(server, /await recoverHistoricalOrderCandidates\(groupId\)/);
assert.match(server, /fetchGroupOrderScanBatch\(groupId, \{ cutoff, batch: 50, includeOutgoing: true \}\)/);
assert.match(server, /recovery\.source = "order-scan"/);
assert.doesNotMatch(server, /await fetchGroupHistory\(groupId, 300, \{ includeOutgoing: true \}\)/);
assert.match(server, /await recoverPendingAcceptanceMessages\(groupId\)/);
assert.match(server, /const scan = \{ messages: Array\.isArray\(fastScan\.messages\)/);
assert.match(server, /message\?\._data\?\.quotedMsg\?\.id\?\._serialized/);
assert.match(server, /async function getQuotedMessageWithFallback\(message\)/);
assert.match(server, /const quoted = await getQuotedMessageWithFallback\(msg\)/);
assert.match(server, /Array\.from\(pendingSourceIds\)\.find\(\(pendingSourceId\) => sourceMessageIdsEqual\(pendingSourceId, sourceId\)\)/);
assert.match(server, /const senderPhone = message\.fromMe\s*\? connectedBotPhone\(\)\s*:\s*await resolveMessageSenderPhone\(message\)/);
assert.match(server, /historical_order_producer_unresolved/);
assert.match(server, /if \(!insertedMessage\.changes && !captainAcceptance\) return;/);
assert.match(server, /acceptance_message_replayed_after_duplicate_guard/);
assert.match(server, /const authorizedThumb = botProducer \? true : Boolean\(reactionPresentOnAcceptance\)/);
assert.match(server, /reaction_target_not_selected_quoted_reply/);
assert.match(server, /sourceMessageIdsEqual\(quotedReplyId, pending\.source_message_id\)/);
assert.match(server, /confirmingCaptainFeeCents/);
console.log("hidden candidate confirmation guardrails verified");
